#!/usr/bin/env ruby
# coding: utf-8

require "yaml"

exit 1 unless ARGV.size.eql? 2 and File.exists? ARGV[0]

y = YAML.load_file ARGV[0]

f = File.open ARGV[1], "w"

if f.closed?
    exit 1
end

f.write y.to_yaml

f.close
