#!/usr/bin/env ruby
# coding: utf-8

require "erb"
require "yaml"

exit 1 unless ARGV.size.eql? 3 and File.exists? ARGV[0] and File.exists? ARGV[1]

fi = File.open ARGV[1], "r"

exit 1 if fi.closed?

r = fi.read

fi.close

config = YAML.load_file ARGV[0]

e = ERB.new r

fo = File.open ARGV[2], "w"

exit 1 if fo.closed?

fo.write e.result binding

fo.close
